apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: databases.redis.com
spec:
  group: redis.com
  scope: Namespaced
  names:
    kind: Database
    plural: databases
    shortNames:
      - "db"
      - "dbs"
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                architecture:
                  type: string
                  enum: ["standalone", "replication"]
                statestore:
                  type: object
                  properties:
                    name:
                      type: string
          required:
          - architecture
