apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.redis.com
spec:
  group: redis.com
  names:
    kind: xDatabase
    plural: xdatabases
    shortNames:
      - "xdb"
      - "xdbs"
  claimNames:
    kind: DatabaseClaim
    plural: databaseclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                architecture:
                  type: string
                  enum: ["standalone", "replication"]
                statestore:
                  type: object
                  properties:
                    name:
                      type: string
                pubsub:
                  type: object
                  properties:
                    name:
                      type: string
          required:
          - architecture
