apiVersion: redis.com/v1alpha1
kind: DatabaseClaim
metadata:
  name: my-db
spec:
  compositionSelector:
    matchLabels:
      provider: local
      type: dapr-dev
  namespace: default
  architecture: replication
  statestore:
    name: statestore
