---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dapr-dashboard-ingress
  namespace: dapr-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dapr.<ENV-NAME>-<ENV-USER-ID>-01.<ENV-ANIMAL>.<ENV-DOMAIN>`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: dapr-dashboard
          port: 8080